### ISSUE TITLE
How to publish lidar data do /filtered_cloud

### ISSUE THREAD

**Issue by thelineover** [praveen-palanisamy/multiple-object-tracking-lidar#12]
first of all, Thank you for this great project.
I have one question for this kf_tracker
now, I'm using velodyne VLP-16 lidar, How can I publish vlp-16 pointcloud to /filtered_cloud??
please, Some direction for this question.
Thank you :)

**Comment by praveen-palanisamy** [comment]
@thelineover : I hope you got all the information you needed. Closing this item. Re-open or create a new one if you need more assistance.
