### ISSUE TITLE
error

### ISSUE THREAD

**Issue by VijeetBenni** [praveen-palanisamy/multiple-object-tracking-lidar#13]
After following all instructions from ReadMe, when I run 
_**$ rosrun multi_object_tracking_lidar kf_tracker**_
I am getting the below error.

/catkin_ws/devel/lib/multi_object_tracking_lidar/kf_tracker: error while loading shared libraries: libopencv_video3.so.3.3: cannot enable executable stack as shared object requires: Invalid argument

I am using kinect ros.

**Comment by praveen-palanisamy** [comment]
@VijeetBenni : I am closing the issue since a resolution for your setup was provided. Feel free to re-open or create a new one if your issue still persists.
