### ISSUE TITLE
obstacle detection problem

### ISSUE THREAD

**Issue by Zhang-Qinghui** [praveen-palanisamy/multiple-object-tracking-lidar#17]
hi,thanks for your work.Does the project  only detect dynamic obstacles?

**Comment by praveen-palanisamy** [comment]
Hi @Zhang-Qinghui , thank you for your interest in this project. The code supports detection, classification and tracking of both dynamic and static obstacles.

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply. I got it. If I fix the velodyne, How can I modify the code to only detect dynamic obstacles.

**Comment by praveen-palanisamy** [comment]
You can apply a filter over the detected objects to remove objects whose velocity is zero. In other words, if there is no change in the position of an objects in `n` consecutive frames, you can treat that to be stationary and filter it out.

**Comment by Zhang-Qinghui** [comment]
what you said is meaningful.Thank you.

**Comment by Zhang-Qinghui** [comment]
But I can not find the direction arrow as your picture shows when I see the reault through rviz. I can see cluster_0, cluster_1, …, cluster_5 topics and the markers on viz topic through rviz. How can I see the direction arrow as your picture shows? thank you in advance.
![2019-11-14 15-53-04屏幕截图](https://user-images.githubusercontent.com/49428118/68837165-f461e800-06f6-11ea-82f5-8f07ec3eda84.png)

**Comment by praveen-palanisamy** [comment]
The markers on the viz topic should look similar on RViz as shown in this project's repo README depending on your point cloud data.

Can you share a screenshot of your visualization to see what's missing in your RViz?

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply.There is the screenshot of my visualization.In additon,only the Fixed Frame set as 'map' can I see the marker.
![2019-11-17 09-50-36屏幕截图](https://user-images.githubusercontent.com/49428118/69001803-10949d80-0920-11ea-9004-36af258822c6.png)

**Comment by praveen-palanisamy** [comment]
I see. So, the objects from the point clouds are being detected, clustered and tracked. The missing piece is that the point clouds are not shown on RViz which is why you don't see the additional information. Please make sure that the point cloud data is published on to the **filtered_cloud** ROS topic and in RViz, choose that topic for "PointCloud2". You should then see all the information. 

Yes. The **map** "FIced Frame" sounds right.

**Comment by Zhang-Qinghui** [comment]
Maybe I do not say clear. I mean, I can't see the arrow as your picture shows, just as the picture shows below .
![2019-11-17 10-29-01屏幕截图](https://user-images.githubusercontent.com/49428118/69002214-77688580-0925-11ea-80f5-319b7f89c270.png)

**Comment by praveen-palanisamy** [comment]
The "arrow" like line segments are derived from the point clouds and will only show up when the point cloud data is streamed into RViz (using the steps in my previous comment).

**Comment by Zhang-Qinghui** [comment]
ok,thank you.
