### ISSUE TITLE
Detecting/Segmenting static objects 

### ISSUE THREAD

**Issue by abhigoku10** [praveen-palanisamy/multiple-object-tracking-lidar#18]
@praveen-palanisamy  hi thanks for opensourcing your code i have few queries 
1. i need to detect/segment static objects like trees / light post / traffic lights/buildings is it possible 
2. if so what method are  you using since using the static objects i need to localize the position 
thanks in advance

**Comment by praveen-palanisamy** [comment]
Yes. You can use the `obj_ids` and the `cluster_i` output by this package to detect/segment the static objects of interest.
The `cluster_i` will give the position of a segmented object to help you localize the object in the given scene.

**Comment by praveen-palanisamy** [comment]
Closing this assuming the response above addressed your question. Re-open or create a new issue if you need more help.
