### ISSUE TITLE
How to publish las file to filtered cloud?

### ISSUE THREAD

**Issue by SkylerZheng45** [praveen-palanisamy/multiple-object-tracking-lidar#27]
Thanks for the great project!
Since the project supports point cloud datasets, may I ask how I can publish my las file to filtered cloud? I'm just totally lost about how to make the project run on the las file.

**Comment by praveen-palanisamy** [comment]
Hi @SkylerZheng45  !

You could run a ROS node that reads the pointcloud data from your LAS file and publishes it to the `filtered_cloud` topic.

Another way that I can think of is to convert the LAS file into [PCD file](http://pointclouds.org/documentation/tutorials/pcd_file_format.html) and use the [pcd_to_pointcloud](http://wiki.ros.org/pcl_ros#pcd_to_pointcloud) node to publish the data.

Hope that helps.

**Comment by praveen-palanisamy** [comment]
Closing this as a couple of resolution methods were proposed. Please re-open if more help is needed.
