### ISSUE TITLE
How to use LaserScan messages instead of PointCloud2?

### ISSUE THREAD

**Issue by chumingqian** [praveen-palanisamy/multiple-object-tracking-lidar#28]
Closing the issue as the question was answered. Reopen if you need more info. Thanks!

_Originally posted by @praveen-palanisamy in https://github.com/praveen-palanisamy/multiple-object-tracking-lidar/issues/9#issuecomment-525173447_

**Comment by chumingqian** [comment]
Hi,palanisamy:
     @praveen-palanisamy  thanks  for  your sharing,  and  i  have a question.  
  In  src/main.cpp    line 21 :  #include <sensor_msgs/PointCloud2.h>
 data type  is  pointCloud2.msg.
 However , my  data type  is  a  LaserScan.msg.   When  i  run the code, i got the  error sth  about  datatype  mistake,   how should  i  solve  this , could  you  give  a  guide , thanks in advance .

![pointCloud2](https://user-images.githubusercontent.com/46816091/88809967-501dc400-d1e7-11ea-90a6-692529358322.jpg)
![laserScan](https://user-images.githubusercontent.com/46816091/88809977-53b14b00-d1e7-11ea-888b-2c3cde1397be.jpg)

**Comment by praveen-palanisamy** [comment]
Hi @chumingqian , 
You can use the [laser_geometry](http://wiki.ros.org/laser_geometry) ROS package to convert your `LaserScan` messages to `PointCloud2` message.
Here's a code example:

```c++
laser_geometry::LaserProjection projector_;

void scanCallback (const sensor_msgs::LaserScan::ConstPtr& scan_in)
{
  sensor_msgs::PointCloud2 point_cloud;
  projector_.projectLaser(*scan_in, point_cloud);

  // You can now use point_cloud
}
```

**Comment by chumingqian** [comment]
> Hi @chumingqian ,
> You can use the [laser_geometry](http://wiki.ros.org/laser_geometry) ROS package to convert your `LaserScan` messages to `PointCloud2` message.
> Here's a code example:
> 
> ```c++
> laser_geometry::LaserProjection projector_;
> 
> void scanCallback (const sensor_msgs::LaserScan::ConstPtr& scan_in)
> {
>   sensor_msgs::PointCloud2 point_cloud;
>   projector_.projectLaser(*scan_in, point_cloud);
> 
>   // You can now use point_cloud
> }
> ```

It  worked  ,thank  you  so  much!!!
