### ISSUE TITLE
VLP 32C Data Interpertation

### ISSUE THREAD

**Issue by SHamblin** [praveen-palanisamy/multiple-object-tracking-lidar#35]
Thanks for the work you've put into the project! 
I've got a question about using it with a VLP 32C. I'm attempting to detect a car in a parking lot and the clusters that are being picked up don't seem to match what I would expect.

I'm playing back the data from a bag file and remapping to the filtered_cloud topic. In the shots of Rviz bellow you can see the input data and then in white the detected clusters. 

Is there a variable that I should adjust? 
`<ec.setClusterTolerance (0.08); >` Seems like a promising line to adjust but I'm unsure if I should increase or lower it.

![2020-09-09 21_13_59-Window](https://user-images.githubusercontent.com/16627235/92670563-4907cc80-f2e2-11ea-83ce-2ab877bcdcbb.png)
![2020-09-09 21_15_01-Window](https://user-images.githubusercontent.com/16627235/92670561-4907cc80-f2e2-11ea-9f67-c66325f73819.png)

Any help would be appreciated, Thank you!

**Comment by praveen-palanisamy** [comment]
Hi @SHamblin , 
In your use-case, is the car that you are intending to detect & track stationary or moving (w.r.t the VLP 32C)?
For this tracker to work without modifications, the point cloud input is expected to be "*filtered*" before publishing onto the `filtered_cloud` topic.
You could pre-process your LiDAR point clouds to remove the stationary points belonging to the background (concentric lines etc) and then publish to the `filtered_cloud` topic to feed this node.

**Comment by praveen-palanisamy** [comment]
Closing this as the question was answered. Please re-open if more information/clarification is needed.
