### ISSUE TITLE
What are the classes in which the code classifies the objects? Any accuracy metric available? What is the speed you are getting?

### ISSUE THREAD

**Issue by Surajj4837-th** [praveen-palanisamy/multiple-object-tracking-lidar#43]
What are the classes in which the code classifies the objects? Any accuracy metric available? What is the speed you are getting?

**Comment by praveen-palanisamy** [comment]
Hi @Surajj4837-th. Missed this question from you until now. Please see my answers below:

> What are the classes in which the code classifies the objects? Any

Any static/dynamic object is detected and tracked. The clustering of pointclouds into an object happens in an unsupervised way so there's no "class labels" associated with them.

> Any accuracy metric available?

No. It's been mainly used on live pointcloud streams and wasn't benchmarked on a static dataset which has annotations to get such metrics.

>What is the speed you are getting?

IIRC, the results were published >=30FPS. It depends on the number of points in the pointcloud and the hardware this is running

**Comment by Surajj4837-th** [comment]
Thanks for the update.

**Comment by boazMgm** [comment]
Hi,
Is there a way to track only dynamic objects?
Thanks a lot.
