### ISSUE TITLE
Invalid argument "/map"

### ISSUE THREAD

**Issue by brianjohnzhang** [praveen-palanisamy/multiple-object-tracking-lidar#45]
It looks like TF2 has deprecated the "/" that precedes frame names so that it should just be "map" instead of "/map". I was able to fix a "Frame not found" error in rviz by removing the slash in main.cpp and main_naive.cpp, so it might be a nice quick fix. Thanks!

https://github.com/praveen-palanisamy/multiple-object-tracking-lidar/blob/f1aec75f7dd46d5f6af3b131be4354822e63c587/src/main.cpp#L250

**Comment by praveen-palanisamy** [comment]
Thanks @brianjohnzhang! That's right, the `/` prefix was only retained initially in `TF2` for backward compatibility with TF but it's indeed deprecated and should be removed. I'll push the fix in a PR.
