### ISSUE TITLE
ROS node hangs when running

### ISSUE THREAD

**Issue by FixedSpecialty** [praveen-palanisamy/multiple-object-tracking-lidar#47]
I saw a similar issue and followed all the steps/read the articles [Understanding ROS Topics](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics) and [Introduction to Working With Laser Scanner Data](http://wiki.ros.org/laser_pipeline/Tutorials/IntroductionToWorkingWithLaserScannerData). The issue I am having is that even after publishing the bag file to the filtered_cloud node,`rosrun multi_object_tracking_lidar kf_tracker` still hangs at `About to setup callback`. The bag file's topic publishes to /livox/lidar so I am "forwarding" it to /filtered_cloud.

I am running in separate terminals on Windows 10 in Ubuntu 18.04 LTS terminals:
 `roscore`
`rosrun multi_object_tracking_lidar kf_tracker` - After running this it hangs on `About to setup callback` forever!
`rosbag play --clock /mnt/d/RosBags/demo2.bag /livox/lidar:=/filtered_cloud`
`rosparam set use_sim_time true` and `rosrun tf static_transform_publisher 0 0 0 0 0 0 map dummy_frame 100`

After all these commands, and publishing I am stuck on the `About to setup callback` message. Any help is greatly appreciated!

The image below shows my RVIZ setup as well.
![image](https://user-images.githubusercontent.com/42878649/140819222-1a03a434-9e8d-4120-9209-48e1af2e467a.png)

**Comment by FixedSpecialty** [comment]
Delay was caused by a lack of processing power. When pausing the rosbag halfway through while everything is running. The kf_tracker would actually run around 2 minutes later.

**Comment by praveen-palanisamy** [comment]
Hi @FixedSpecialty , Thanks for summarizing the issue you faced and following it up with the reason and resolution. It's going to be helpful for the community. I appreciate it!
