### ISSUE TITLE
How to publish the RPLidar Data to the Filtered_Cloud rostopic

### ISSUE THREAD

**Issue by tilexiadam** [praveen-palanisamy/multiple-object-tracking-lidar#51]
Thank you for this source and sorry if this question has already been answered but I could not manage to do this. 

I am using an Slamtec RPlidar and here is a screenshot from RViz:

![WhatsApp Image 2022-02-18 at 03 22 26](https://user-images.githubusercontent.com/99930615/154595402-c8a1a7ca-541b-4843-b881-5c8c903f70c2.jpeg)

The problem is, I couldn't figure how to publish the rplidar scan data onto the filtered_cloud rostopic

**Comment by aldras** [comment]
Please see https://github.com/praveen-palanisamy/multiple-object-tracking-lidar/issues/48

**Comment by aldras** [comment]
Alter the topic, in the above mentioned "issue" and change it to "scan" as I see in your image.
This should grab the point cloud data from your device, if it is indeed outputting on the "scan" topic.

**Comment by praveen-palanisamy** [comment]
@aldras : Thank you for your comments!

@tilexiadam : If you are still facing this issue, please try [this solution](https://github.com/praveen-palanisamy/multiple-object-tracking-lidar/issues/48#issuecomment-1134177467). You can rename your existing pointcloud topic (`scan` from your screenshot) to `filtered_cloud` using one of the following:
1. In roslaunch file: `<remap from="scan" to="filtered_cloud"/>`
1. On the command-line: `rosrun sensor_pkg_name sensor_node_name scan:=filtered_cloud`

**Comment by praveen-palanisamy** [comment]
Closing this since the question has been answered. Feel free to post if you still need help.
