### ISSUE TITLE
Paper and lidar

### ISSUE THREAD

**Issue by NamDinhRobotics** [praveen-palanisamy/multiple-object-tracking-lidar#7]
Hello, your code is really interesting 
Would you give me the paper that you referenced?
And the lidar in this code is 2D or 3D?

Thank you so much,
Best regards,
Nam Dinh

**Comment by praveen-palanisamy** [comment]
@NamDinhRobotics : Thanks for your interest. 
This work was not based on any paper specifically. 
The code supports both 2D and 3D pointclouds from LIDAR or other pointcloud data generators.

**Comment by NamDinhRobotics** [comment]
Thank you so much for your response. :)

**Comment by praveen-palanisamy** [comment]
You are welcome!
Closing this issue. Feel free to open a new one if you have any other issue/question.
